server:
  port: 8083

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          label: main
          uri: https://github.com/vivekPandeyDev/config
          clone-on-start: true

